Description: >
  Opebiyi Abdul-Lateef / Udacity
  This template deploys VPC, with pair of public and private subnet
  accross two Availability Zone. It deploys a NAT gateway for network
  access for the private network. It deploys internet gateway to provide
  public access.

Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to  resource names
    Type: String

  VpcCIDR:
    Description: Please enter the IP range (CIDR notation) for this VPC
    Type: String

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsHostnames: true
      Tags:
        - Key: name
          Value: !Ref EnvironmentName
